### ISSUE TITLE
meals$ observable type error

### ISSUE THREAD

**Issue by evgeniush** [UltimateAngular/angular-pro-app-seed#6]
Hey Todd,

In MealsService defining meals$ at line 22 I'm having a type error:

meals$: Observable<Meal[]> = this.db.list(`meals/${this.uid}`)
    .do(next => this.store.set('meals', next));

Type 'Observable<{}>' is not assignable to type 'Observable<Meal[]>'.
  Type '{}' is not assignable to type 'Meal[]'.
    Property 'includes' is missing in type '{}'.

which should not be there according to AngularFireDatabase.list definition

(method) AngularFireDatabase.list(pathOrRef: PathReference, opts?: FirebaseListFactoryOpts): FirebaseListObservable<any[]>
 
Any help?

angular-pro-app-seed/src/health/shared/services/meals/meals.service.ts
Branch: 09-meals-component
node 8
Windows 10

![screen shot 2018-03-06 at 10 02 06 am](https://user-images.githubusercontent.com/375454/37039782-4c226a8c-2126-11e8-91f1-9bfe36f7d6b9.png)
![screen shot 2018-03-06 at 10 14 12 am](https://user-images.githubusercontent.com/375454/37040225-535fdacc-2127-11e8-9570-431b88794920.png)

**Comment by ibaiimaz** [comment]
You can explicitly set the type using the current example:

```
meals$: Observable<Meal[]> = (this.db.list(\`meals/${this.uid}`) as Observable<Meal[]>)
  .do(next => this.store.set('meals', next));
```

I'm not sure if it's a good practice but it works.

Hope it helps!

**Comment by evgeniush** [comment]
no, but still, db.list returns not correct data type

[ts] Type 'AngularFireList<{}>' cannot be converted to type 'Observable<Meal[]>'.
[ts]
Type 'AngularFireList<{}>' cannot be converted to type 'Observable<Meal[]>'.
  Property '_isScalar' is missing in type 'AngularFireList<{}>'.

**Comment by hypocore** [comment]
What I've posted above works, but valueChanges does not return the key that is required in further videos. To get the key, you would have to use snapshotChanges() and map the key to each meal in the meals array.

In meals.service.ts:
    meals$: Observable<Meal[]> = this.db.list<Meal>(`meals/${this.uid}`).snapshotChanges()
    .pipe(
        map(meals => 
            meals.map(meal => ({ $key: meal.key, ...meal.payload.val() }))
          ),
        tap(meals => this.store.set('meals', meals))
    );

which is probably like this using the old operators:
    meals$: Observable<Meal[]> = this.db.list<Meal>(`meals/${this.uid}`).snapshotChanges()
        .map(meals => 
            meals.map(meal => ({ $key: meal.key, ...meal.payload.val() }))
          )
        .do(meals => this.store.set('meals', meals))

**Comment by ikehiemma** [comment]
@hypocore I have used snapshotChanges() as you've implemented above in meals.service.ts, but I keep getting the error that **$key** is undefined when I use it in the list-item component. 

```
    getRoute(item: any){
        return [`../meals`, item.$key];
    }
```

Is there a way I can get this to work? Thanks.
